// Generated by tools/gen-constants.mjs from dom-expressions — do not edit by hand.

pub(crate) static PROPERTIES: &[&str] = &[
    "className",
    "value",
    "readOnly",
    "formNoValidate",
    "isMap",
    "noModule",
    "playsInline",
    "allowfullscreen",
    "async",
    "autofocus",
    "autoplay",
    "checked",
    "controls",
    "default",
    "disabled",
    "formnovalidate",
    "hidden",
    "indeterminate",
    "ismap",
    "loop",
    "multiple",
    "muted",
    "nomodule",
    "novalidate",
    "open",
    "playsinline",
    "readonly",
    "required",
    "reversed",
    "seamless",
    "selected",
];

pub(crate) static CHILD_PROPERTIES: &[&str] =
    &["innerHTML", "textContent", "innerText", "children"];

pub(crate) static DELEGATED_EVENTS: &[&str] = &[
    "beforeinput",
    "click",
    "dblclick",
    "contextmenu",
    "focusin",
    "focusout",
    "input",
    "keydown",
    "keyup",
    "mousedown",
    "mousemove",
    "mouseout",
    "mouseover",
    "mouseup",
    "pointerdown",
    "pointermove",
    "pointerout",
    "pointerover",
    "pointerup",
    "touchend",
    "touchmove",
    "touchstart",
];

pub(crate) static SVG_ELEMENTS: &[&str] = &[
    "altGlyph",
    "altGlyphDef",
    "altGlyphItem",
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "circle",
    "clipPath",
    "color-profile",
    "cursor",
    "defs",
    "desc",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDistantLight",
    "feFlood",
    "feFuncA",
    "feFuncB",
    "feFuncG",
    "feFuncR",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMergeNode",
    "feMorphology",
    "feOffset",
    "fePointLight",
    "feSpecularLighting",
    "feSpotLight",
    "feTile",
    "feTurbulence",
    "filter",
    "font",
    "font-face",
    "font-face-format",
    "font-face-name",
    "font-face-src",
    "font-face-uri",
    "foreignObject",
    "g",
    "glyph",
    "glyphRef",
    "hkern",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "metadata",
    "missing-glyph",
    "mpath",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "set",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tref",
    "tspan",
    "use",
    "view",
    "vkern",
];

pub(crate) static VOID_ELEMENTS: &[&str] = &[
    "area", "base", "br", "col", "embed", "hr", "img", "input", "keygen", "link", "menuitem",
    "meta", "param", "source", "track", "wbr",
];

pub(crate) static INLINE_ELEMENTS: &[&str] = &[
    "a", "abbr", "acronym", "b", "bdi", "bdo", "big", "br", "button", "canvas", "cite", "code",
    "data", "datalist", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd",
    "label", "map", "mark", "meter", "noscript", "object", "output", "picture", "progress", "q",
    "ruby", "s", "samp", "script", "select", "slot", "small", "span", "strong", "sub", "sup",
    "svg", "template", "textarea", "time", "u", "tt", "var", "video",
];

pub(crate) static BLOCK_ELEMENTS: &[&str] = &[
    "address",
    "article",
    "aside",
    "blockquote",
    "dd",
    "details",
    "dialog",
    "div",
    "dl",
    "dt",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "header",
    "hgroup",
    "hr",
    "li",
    "main",
    "menu",
    "nav",
    "ol",
    "p",
    "pre",
    "section",
    "table",
    "ul",
];

pub(crate) static ALWAYS_CLOSE: &[&str] = &[
    "title", "style", "a", "strong", "small", "b", "u", "i", "em", "s", "code", "object", "table",
    "button", "textarea", "select", "iframe", "script", "template", "fieldset",
];

pub(crate) static ALIASES: &[(&str, &str)] = &[("className", "class"), ("htmlFor", "for")];

pub(crate) static SVG_NAMESPACE: &[(&str, &str)] = &[
    ("xlink", "http://www.w3.org/1999/xlink"),
    ("xml", "http://www.w3.org/XML/1998/namespace"),
];

pub(crate) static RESERVED_NAMESPACES: &[&str] =
    &["class", "on", "oncapture", "style", "use", "prop", "attr"];

pub(crate) static NON_SPREAD_NAMESPACES: &[&str] = &["class", "style", "use", "prop", "attr"];

/// `PropAliases` from dom-expressions: an alias plus the tag names it applies to.
/// An empty tag list means the alias applies to every tag.
static PROP_ALIASES: &[(&str, &str, &[&str])] = &[
    ("class", "className", &[]),
    ("formnovalidate", "formNoValidate", &["BUTTON", "INPUT"]),
    ("ismap", "isMap", &["IMG"]),
    ("nomodule", "noModule", &["SCRIPT"]),
    ("playsinline", "playsInline", &["VIDEO"]),
    ("readonly", "readOnly", &["INPUT", "TEXTAREA"]),
];

pub(crate) fn get_prop_alias(prop: &str, tag_name: &str) -> Option<&'static str> {
    let (_, alias, tags) = PROP_ALIASES.iter().find(|(p, _, _)| *p == prop)?;
    if tags.is_empty() || tags.contains(&tag_name) {
        Some(alias)
    } else {
        None
    }
}
