// Generated by tools/gen-constants.mjs from validate-html-nesting — do not edit by hand.

pub(crate) static ONLY_VALID_CHILDREN: &[(&str, &[&str])] = &[
    ("colgroup", &["col"]),
    (
        "head",
        &[
            "base",
            "basefront",
            "bgsound",
            "link",
            "meta",
            "noframes",
            "noscript",
            "script",
            "style",
            "template",
            "title",
        ],
    ),
    ("iframe", &[]),
    ("math", &["mrow"]),
    ("optgroup", &["option"]),
    ("option", &[]),
    ("script", &[]),
    ("select", &["optgroup", "option"]),
    ("style", &[]),
    ("table", &["caption", "colgroup", "tbody", "tfoot", "thead"]),
    ("tbody", &["tr"]),
    ("textarea", &[]),
    ("tfoot", &["tr"]),
    ("thead", &["tr"]),
    ("title", &[]),
    ("tr", &["td", "th"]),
];

pub(crate) static ONLY_VALID_PARENTS: &[(&str, &[&str])] = &[
    ("area", &["map"]),
    ("body", &["html"]),
    ("caption", &["table"]),
    ("col", &["colgroup"]),
    ("colgroup", &["table"]),
    ("dd", &["div", "dl"]),
    ("dt", &["div", "dl"]),
    ("figcaption", &["figure"]),
    ("head", &["html"]),
    ("html", &[]),
    ("summary", &["details"]),
    ("tbody", &["table"]),
    ("td", &["tr"]),
    ("tfoot", &["table"]),
    ("th", &["tr"]),
    ("thead", &["table"]),
    ("tr", &["tbody", "tfoot", "thead"]),
];

pub(crate) static KNOWN_INVALID_CHILDREN: &[(&str, &[&str])] = &[
    (
        "p",
        &[
            "address",
            "article",
            "aside",
            "blockquote",
            "center",
            "details",
            "dialog",
            "dir",
            "div",
            "dl",
            "fieldset",
            "figure",
            "footer",
            "form",
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "header",
            "hgroup",
            "hr",
            "input",
            "li",
            "main",
            "menu",
            "nav",
            "ol",
            "p",
            "pre",
            "section",
            "table",
            "ul",
        ],
    ),
    (
        "svg",
        &[
            "b",
            "blockquote",
            "br",
            "code",
            "dd",
            "div",
            "dl",
            "dt",
            "em",
            "embed",
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "hr",
            "i",
            "img",
            "li",
            "menu",
            "meta",
            "ol",
            "p",
            "pre",
            "ruby",
            "s",
            "small",
            "span",
            "strong",
            "sub",
            "sup",
            "table",
            "u",
            "ul",
            "var",
        ],
    ),
];

pub(crate) static KNOWN_INVALID_PARENTS: &[(&str, &[&str])] = &[
    ("a", &["a"]),
    ("button", &["button"]),
    ("dd", &["dd", "dt"]),
    ("dt", &["dd", "dt"]),
    ("form", &["form"]),
    ("h1", &["h1", "h2", "h3", "h4", "h5", "h6"]),
    ("h2", &["h1", "h2", "h3", "h4", "h5", "h6"]),
    ("h3", &["h1", "h2", "h3", "h4", "h5", "h6"]),
    ("h4", &["h1", "h2", "h3", "h4", "h5", "h6"]),
    ("h5", &["h1", "h2", "h3", "h4", "h5", "h6"]),
    ("h6", &["h1", "h2", "h3", "h4", "h5", "h6"]),
    ("li", &["li"]),
];

fn lookup<'a>(table: &'a [(&str, &'a [&str])], key: &str) -> Option<&'a [&'a str]> {
    table
        .binary_search_by(|(name, _)| (*name).cmp(key))
        .ok()
        .map(|index| table[index].1)
}

/// `isValidHTMLNesting(parent, child)`.
pub(crate) fn is_valid_html_nesting(parent: &str, child: &str) -> bool {
    if let Some(valid) = lookup(ONLY_VALID_CHILDREN, parent) {
        return valid.contains(&child);
    }
    if let Some(valid) = lookup(ONLY_VALID_PARENTS, child) {
        return valid.contains(&parent);
    }
    if let Some(invalid) = lookup(KNOWN_INVALID_CHILDREN, parent)
        && invalid.contains(&child)
    {
        return false;
    }
    if let Some(invalid) = lookup(KNOWN_INVALID_PARENTS, child)
        && invalid.contains(&parent)
    {
        return false;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::is_valid_html_nesting;

    #[test]
    fn matches_validate_html_nesting() {
        assert!(!is_valid_html_nesting("p", "div"));
        assert!(!is_valid_html_nesting("table", "tr"));
        assert!(is_valid_html_nesting("ul", "li"));
        assert!(is_valid_html_nesting("div", "span"));
        // `head` only accepts a known list.
        assert!(is_valid_html_nesting("head", "meta"));
        assert!(!is_valid_html_nesting("head", "div"));
        // An unknown tag on either side is left alone.
        assert!(is_valid_html_nesting("whatever", "div"));
    }
}
